--Created table users
CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50),
	EMAIL VARCHAR(50) UNIQUE,
	JOIN_DATE DATE
);

--created table movies
CREATE TABLE MOVIES (
	MOVIE_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100),
	GENRE VARCHAR(50),
	RELEASE_YEAR INT
);

--created table subscription
CREATE TABLE SUBSCRIPTIONS (
	SUBSCRIPTION_ID SERIAL PRIMARY KEY,
	USER_ID INTEGER,
	END_DATE DATE,
	START_DATE DATE,
	PLAN VARCHAR(20),
	PRICE NUMERIC(8, 2),
	CONSTRAINT FK_SUBS_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

--created table views
CREATE TABLE VIEWS (
	VIEW_ID SERIAL PRIMARY KEY,
	USER_ID INTEGER,
	MOVIE_ID INTEGER,
	WATCH_DATE DATE,
	WATCH_DURATION INTEGER,
	CONSTRAINT FK_VIEW_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_VIEW_MOVIEID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES (MOVIE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);