--Use the Sakila Database in MySQL workbench and frame the SQL queries for below scenarios. 


--Q1. Write a query to display the first name, last name, and rental date of all customers who rented a film. Use the customer and rental tables. 

select c.first_name, c.last_name, r.rental_date 
from customer c 
inner join rental r 
on c.customer_id = r.customer_id;


--Q2. Write a query to display the first name, last name, and address of all customers whose district is either Alberta or Texas. Use the customer and address tables. 

select c.first_name, c.last_name, a.address 
from customer c 
left join address a 
on c.address_id = a.address_id 
where a.district in ('Alberta','Texas');


--Q3. List all films along with their category names, including films that may not belong to any category. Then sort it by category names. Use the film, film_category and category tables. 

select f.film_id, f.title, c.name 
from film f 
left join film_category fc 
on f.film_id = fc.film_id 
left join category c 
on fc.category_id=c.category_id 
order by c.name;


--Q4. Display the number of rentals per store. Use the rental, inventory, and store tables.

select s.store_id, count(r.rental_id) as total_rentals 
from rental r 
inner join inventory i 
on r.inventory_id = i.inventory_id 
inner join store s 
on i.store_id = s.store_id 
group by s.store_id;


--Q5. List the names of categories that have more than 50 films. Use table category and film_category. 

select c.name 
from film_category f 
inner join category c 
on f.category_id = c.category_id 
group by c.name 
having count(*)>50;


--Q6. Write a Query to display the film titles that have been rented by the customer named 'Mary Smith'. Use a subquery to get the customer ID. 

select distinct f.title 
from film f 
inner join inventory i 
on f.film_id = i.film_id 
inner join rental r 
on r.inventory_id=i.inventory_id 
where r.customer_id = (select customer_id from customer where first_name = 'Mary' and last_name='Smith');


--Q7. Write a query to display the total rental income generated by each film. Use film, inventory, rental and payment tables. 

select f.film_id, f.title, sum(p.amount) as rent_inc_generated 
from film f 
inner join inventory i 
on f.film_id = i.film_id 
inner join rental r 
on r.inventory_id = i.inventory_id 
inner join payment p 
on  p.rental_id = r.rental_id 
group by f.film_id, f.title 
order by rent_inc_generated desc;


--Q8. Write a query to display the total number of films each actor has acted in. Use actor, film_Actor tables. 

select concat(a.first_name,' ', a.last_name) as Actor_name, count(f.film_id) as 
films 
from actor a 
inner join film_actor f 
on a.actor_id = f.actor_id 
group by a.actor_id, a.first_name, a.last_name 
order by films desc;


--Q9. Write a query to list all rentals with a case statement that displays 'New Customer' if the customer_id is greater than 300, and 'Regular Customer' otherwise. Use table rental. 

select rental_id, customer_id, rental_date, 
case when customer_id>300 then 'New Customer' 
else 'Regular Customer' 
end as cust_type 
from rental;


--Q10. Write a --Query to find all films with titles that start with the letter 'A'. Display the film title and the release year. Use film table and  inventory table. 

select title, release_year from film where title like 'A%';


--Q11. Create a new DB and perform below operations using SQL commands. 
--(a) Create a table with 2 columns – Student_ID, Marks 
--(b) Insert 2 records in this table. 
--(c) Rename the Marks column with Score. 
--(d) Then delete the table. 
--(e) Then delete the Database. 

create database dummy; 

use dummy; 

create table students( 
	Student_ID Serial primary key, 
	Marks numeric(3,1) 
); 

insert into students(Marks) 
Values (95),(80); 

alter table students 
rename column Marks to Score; 

drop table students; 

drop database dummy;